/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class', '.theme-dark'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        silo: {
          lightPurple: '#f0f1fe',
          white: '#ffffff',
          softPurple: '#dbe1fa',
          nodePurple: '#c4cefd',
          deepPurple: '#9dadfb',
          signalGreen: '#e1fcad',
          softGreen: '#daecc6',
          mintAccent: '#d0f1d5',
          surfaceLight: '#d7dfea',
          surfaceMuted: '#778ea3',
          surfaceStrong: '#44525f',
          deepSurface: '#232b33',
          black: '#060a0e',
          almostWhite: '#f2f4f7',
          surfaceBlue: '#f5f6fc',
          lightCyan: '#e2f0fb',
          softCyan: '#cce4f5',
          nodeCyan: '#aad2ee',
          strongViolet: '#c7b1e6',
          deepViolet: '#b193dc',
          /* Semantic aliases aligned with globals.css --silo-* */
          bg: '#f0f1fe',
          surface: '#ffffff',
          surfaceSoft: '#f2f4f7',
          border: '#d7dfea',
          text: '#44525f',
          textMuted: '#778ea3',
          accent: '#9dadfb',
        },
        primary: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
        gray: {
          50: '#f9fafb',
          100: '#f3f4f6',
          200: '#e5e7eb',
          300: '#d1d5db',
          400: '#9ca3af',
          500: '#6b7280',
          600: '#4b5563',
          700: '#374151',
          800: '#1f2937',
          900: '#111827',
        },
      },
      fontFamily: {
        sans: ['var(--font-dm-sans)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-dm-mono)', 'ui-monospace', 'monospace'],
      },
    },
  },
  plugins: [],
}
